#index:
#    path: /
#    controller: App\Controller\DefaultController::index
kms_froala_editor:
  resource: '@KMSFroalaEditorBundle/Resources/config/routing.yml'
  prefix:   /froalaeditor
_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.yaml"
